"""add pathforge generated_roadmaps

Revision ID: da6331a3d9e7
Revises: 6520ba02fd4e
Create Date: 2026-04-15 12:20:38.061764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da6331a3d9e7'
down_revision: Union[str, None] = '6520ba02fd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('roadmap', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_roadmaps_id'), 'generated_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_generated_roadmaps_user_id'), 'generated_roadmaps', ['user_id'], unique=False)
    op.drop_index('idx_feedback_rating', table_name='feedback')
    op.drop_index('idx_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    op.alter_column('users', 'reset_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.alter_column('users', 'reset_token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='feedback_rating_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('idx_feedback_user_id', 'feedback', ['user_id'], unique=False)
    op.create_index('idx_feedback_rating', 'feedback', ['rating'], unique=False)
    op.drop_index(op.f('ix_generated_roadmaps_user_id'), table_name='generated_roadmaps')
    op.drop_index(op.f('ix_generated_roadmaps_id'), table_name='generated_roadmaps')
    op.drop_table('generated_roadmaps')
    # ### end Alembic commands ###
